spring.application.name=health-recomendation
server.port=8000

spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true

#spring.datasource.initialization-mode=always
#spring.sql.init.mode=always

spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true



